### PR TITLE
(#146) Fix mcollective fact on windows 1/2

### LINKED ISSUE #146: `mcollective` facts generation is broken on windows
When investigating inconsistent result using PuppetDB discovery and the windows nodes never being returned, I saw that the he `mcollective` fact is broken on this platform:

```
error : LoadError: cannot load such file -- win32/dir
client :


server :


aio_major_version : 7
puppet_major_version : 7
```

### PR DESCRIPTION
**Pull request by smortex**
This is part 1/2 to fix #146

part 2/2 is choria-io/puppet-mcollective#293

### CODE REVIEW

File: lib/mcollective/util.rb [hunk 1]
```diff
@@ -147,13 +147,11 @@ def self.empty_filter
 
     # Returns the PuppetLabs mcollective path for windows
     def self.windows_prefix
-      require "win32/dir"
-      File.join(Dir::COMMON_APPDATA, "PuppetLabs", "choria")
+      File.join(ENV["ALLUSERSPROFILE"], "PuppetLabs", "choria")
```
Comment (ripienaar) [inline lib/mcollective/util.rb:150]: weird, is this a standard environmen var available on all windows machines?

Comment (smortex) [reply lib/mcollective/util.rb:150]: I could not find some "authoritative" answer to this question unfortunately.  The fact that the `win32-*` gems where removed from Puppet and replaced by this; that I found references to this variable in old Microsoft documentation; and that it worked on the system I tried it (latest windows 10 with all updates) made me think it should be okay :-)

We can also add `win32-dir` as an explicit dependency for the mcorpc gem: it does much complicated stuff to get this information, maybe it's safer? I don't know…  :man_shrugging:
