### PR TITLE
(#142) relocate task scripts in spooldir

### LINKED ISSUE #142: Unable to run (some) Bolt tasks which relies on files
According to [bolt documentation](https://puppet.com/docs/bolt/latest/writing_tasks.html#sharing-task-code), a task that use _shared_ files can mention it internally two ways:
 * Using `_installdir` params (e.g. `$PT__installdir` in shell)
 * Using relative path from script dirname

Running bolt task which relies on files mentionned using relative path failed with _choria_/_mco_

Note : In _Bolt_ documentation, `_installdir` param is used in _Ruby_ example, and relative path is used in _Python_ one.

### PR DESCRIPTION
**Pull request by smortex**
When setting up the spooldir, ensure the actual task entry point is copied as `<module name>/tasks/<task-name>`.  This way, tasks referring to other resources using relative path will be able to find them.

Fixes #142

### CODE REVIEW

**Comment by smortex** [comment]
Hum…  It looks like the JSON loaded by the unit test does not look like the JSON returned by the PuppetServer API endpoint.  I added a few commits to fix this.

@neomilium, do you still have a real-world non-working setup that can be used to check if this fix your issue?

File: lib/mcollective/util/tasks_support.rb [hunk 1]
```diff
@@ -569,6 +572,13 @@ def parse_task(task)
         parts
       end
 
+      # Return a task's module
```
Comment (ripienaar) [inline lib/mcollective/util/tasks_support.rb:575]: new line below

File: lib/mcollective/util/tasks_support.rb [hunk 2]
```diff
@@ -569,6 +572,13 @@ def parse_task(task)
...
+      # @param task [String]
+      # @return [String] the module name
```
Comment (ripienaar) [inline lib/mcollective/util/tasks_support.rb:577]: add here ```@raise [StandardError] for invalid task names``` since `parse_task` can fail

**Review by ripienaar — CHANGES_REQUESTED** [review]
looks good, minor changes only

**Comment by ripienaar** [comment]
looks good, you're ready for me to merge?

**Comment by smortex** [comment]
@ripienaar it was okay with my local tests but @neomilium has a real world problem that should be fixed by this and I would like to have feedback from him to be sure it is okay :grin:.

@neomilium overwriting the file directly on the node where the task is run should do it (maybe adjust the Ruby version if the node is not running Puppet 7):

```
# curl -o /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.24.1/lib/mcollective/util/tasks_support.rb \
  https://raw.githubusercontent.com/smortex/mcorpc-ruby-support/relocate-task-file/lib/mcollective/util/tasks_support.rb
```

Does it fix your issue?

**Comment by neomilium** [comment]
I just tested the patch, it works! Thanks

**Comment by neomilium** [comment]
@ripienaar Ready to merge :-)

**Comment by ripienaar** [comment]
Thank you @neomilium and @smortex :)
